---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cache.openshift
  resources:
  - clustermonitoringoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.openshift
  resources:
  - clustermonitoringoperators/finalizers
  verbs:
  - update
- apiGroups:
  - cache.openshift
  resources:
  - clustermonitoringoperators/status
  verbs:
  - get
  - patch
  - update
