apiVersion: apiextensions.k8s.io/v1
kind: ClusterMonitoringOperator 
metadata:
  name: clustermonitoringoperator
spec:
  prometheusOperatorConfig:
    nodeSelector:
      type: master
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: type
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            foo: bar
